CREATE TABLE A00922317_user (
  ID int NOT NULL AUTO_INCREMENT,
  username VARCHAR(50),
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  email VARCHAR(50),
  password VARCHAR(50),
  PRIMARY KEY (ID)
);

CREATE TABLE A00922317_user_timeline (
  ID int NOT NULL AUTO_INCREMENT,
  user_id int NOT NULL,
  post_date DATE,
  post_text VARCHAR(200),
  post_time VARCHAR(10),
  viewcount SMALLINT(255) UNSIGNED,
  PRIMARY KEY (ID),
  FOREIGN KEY (user_id) REFERENCES A00922317_user(ID) ON UPDATE CASCADE ON DELETE CASCADE
);
